name: Tablizr
version: 0.0.1
description: Turn any html table into a powerhouse
authors: itenium
homepage: 

environment:
  sdk: ">=2.13.1 <3.0.0"

# Add package?
# dart pub add characters
dependencies: 
  characters: ^1.1.0

dev_dependencies:
  build_runner: ">=1.6.2 <3.0.0"
  build_web_compilers: ">=2.12.0 <4.0.0"

transformers:
- chrome
- $dart2js:
  csp: true
